config/routes.rb
Rails.application.routes.draw do
  # get "/", to: "welcome#home" 
  root "pages#home" 
  get "/about", to: "pages#about"

  # get "/blog", to: "blog#index"
  # get "/blog/new", to: "blog#new"
  # post "/blog", to: "blog#create"
  # get "/blog/:id", to: "blog#show"
  # get "/blog/:id/edit", to: "blog#edit"
  # patch "/blog/:id", to: "blog#update"
  # delete "/blog/:id", to: "blog#destory"

  #REST 直接用resources生出對應路徑
  resources :blogs
  get "/@:handler/blogs/", to: "blogs#show"
  get "/@:handler/blogs/:id", to: "articles#show"
  
  resources :articles do
    resources :comments, shallow: true, only: [:create, :destroy] 
    # 簡短捷徑 裡面三個需要/article id =>only[ index new create ] 外面四個only[]
   
    # member(有 /:id/)
    member do
      # /articles/:id/unlock
      patch :unlock
      post :like
    end
    # patch :unlock on :member
    
  #collection (無 /:id/)
    # collection do 
    # /articles/unlock
      # patch :unlock
    # end
  end

  # namespace 為了做出api開頭的路徑  api/v1/articles/:id/like
  namespace :api do
    namespace :v1 do
      resources :articles, only: [] do
        member do
          post :like
        end
      end
    end
  end
  resource :sessions, only:[:create, :destroy]
  resource :users, except: [:new, :destroy], path: "user" do
    get :sign_up
    get :sign_in
    
  end

  get "/@:handler", to: "blogs#show"
  # 可直接更改所有路徑
  # resources :blogs, path:"helloworld" 
  
  # only只開...
  # resources :blog, only: [:index,:show]
  
  # except除了...都開
  # resources :blog, except: [:index,:new]
  # 可用only 和 except控制那些要開啟

  # get post...都是function
  # 路徑比對由上而下，使用:id比對需要注意，id可以自己改任何字，都可以拿來比對英文字母跟數字，可以一直往後擴增
  # 常被存取的可以擺在最前面
end


# 產生controller
# $ rails g controller pages

# 刪除controller
# $ rails d controller pages

app/models/blog.rb
class Blog < ApplicationRecord
  acts_as_paranoid
  
  #relationship
  has_many :blog_visitors
  has_many :visitors, through: :blog_visitors, source: :user

  belongs_to :user

  #validation
  validates :handler, presence: true, uniqueness: true
  validates :title, presence: true

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :require_login?, only:[:show]
 
  def show
    @blog = Blog.find_by!(handler: params[:handler])

  #   #誰來我家
    if @blog != current_user.blog
      if @blog.visitors.include?(current_user)
        @blog.visitors.destroy(current_user)
      end

      @blog.visitors << current_user
    end
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = current_user.build_blog(blog_params)
    if @blog.save
      redirect_to "/@#{@blog.handler}", notice: "已成功建立 Blog"
    else
      render :new
    end
  end

  def edit
  end

  def destroy
  end

  private
  def blog_params
    params.require(:blog).permit(:handler, :title, :description)
  end

end

app/views/blogs/index.html.erb
<h1>文章列表</h1>
<%# <a href="/blogs/new">新增文章</a> %>
<%= link_to "新增文章", new_blog_path %>



<% @articles.each do |article| %>
<%# 輸出才要加 "=" %>
<ul>
  <li>
     <%#= link_to article.title, article_path(article) %>
     <%= link_to article.title, article %>
     <%= link_to "編輯", edit_article_path(article)%>
     <%= link_to "刪除", article, method: "delete", data: {confirm: "是否刪除?"} %> 
     <%# 上面會產生nofollow的效果，可以防止爬蟲，也可以method包在data內就不會有nofollow %>
  </li>
</ul>

<% end %>
<%#  製作忘記密碼之類的會需要用到url連回來 %>
<%#= link_to "新增文章", new_blog_url %>

app/views/blogs/new.html.erb
<h1>新增Blog</h1>

你還沒有自己的 Blog，趕快新增一個吧！

<%= form_with model: @blog do |form|%>
  <div>
    Blog識別碼: <%= form.text_field :handler%>
  </div>
  <div>
    站名: <%= form.text_field :title%>
  </div>
  <div>
    說明: <%= form.text_area :description%>
  </div>
  <%= form.submit "新增" %>
<% end %>

app/views/blogs/show.html.erb
<h1><%= @blog.title %></h1>