config/routes.rb
Rails.application.routes.draw do
  # get "/", to: "welcome#home" 
  root "pages#home" 
  get "/about", to: "pages#about"

  # get "/blog", to: "blog#index"
  # get "/blog/new", to: "blog#new"
  # post "/blog", to: "blog#create"
  # get "/blog/:id", to: "blog#show"
  # get "/blog/:id/edit", to: "blog#edit"
  # patch "/blog/:id", to: "blog#update"
  # delete "/blog/:id", to: "blog#destory"

  #REST 直接用resources生出對應路徑
  resources :blogs
  get "/@:handler/blogs/", to: "blogs#show"
  get "/@:handler/blogs/:id", to: "articles#show"
  
  resources :articles do
    resources :comments, shallow: true, only: [:create, :destroy] 
    # 簡短捷徑 裡面三個需要/article id =>only[ index new create ] 外面四個only[]
   
    # member(有 /:id/)
    member do
      # /articles/:id/unlock
      patch :unlock
      post :like
    end
    # patch :unlock on :member
    
  #collection (無 /:id/)
    # collection do 
    # /articles/unlock
      # patch :unlock
    # end
  end

  # namespace 為了做出api開頭的路徑  api/v1/articles/:id/like
  namespace :api do
    namespace :v1 do
      resources :articles, only: [] do
        member do
          post :like
        end
      end
    end
  end
  resource :sessions, only:[:create, :destroy]
  resource :users, except: [:new, :destroy], path: "user" do
    get :sign_up
    get :sign_in
    
  end

  get "/@:handler", to: "blogs#show"
  # 可直接更改所有路徑
  # resources :blogs, path:"helloworld" 
  
  # only只開...
  # resources :blog, only: [:index,:show]
  
  # except除了...都開
  # resources :blog, except: [:index,:new]
  # 可用only 和 except控制那些要開啟

  # get post...都是function
  # 路徑比對由上而下，使用:id比對需要注意，id可以自己改任何字，都可以拿來比對英文字母跟數字，可以一直往後擴增
  # 常被存取的可以擺在最前面
end


# 產生controller
# $ rails g controller pages

# 刪除controller
# $ rails d controller pages

app/models/article.rb
class Article < ApplicationRecord
  acts_as_paranoid
  #relationships
  belongs_to :user
  has_many :comments
  has_many :like_articles
  has_many :users, through: :like_articles
  #validaiton
  validates :title, presence: true



  # 假刪除處理 
  # scope :available, -> { where(deleted_at: nil) } 
  # lambda, Callback function
  
  # default scope 不管要不要都會找，這樣就可以在任何地方都只顯示沒被刪除的，有需要查找到已刪除的需要unscope去取消預設
  # default_scope { where(deleted_at: nil) }
  
  # def self.available 
    # 如果有比較多邏輯運算寫這種
    # 可以把所有商業運作邏輯用在model這裡
    # ex 之後想找出所有同類型可以在這邊運作
    # where(deleted_at: nil)
  # end

  # def destroy
  #   update(deleted_at: Time.now)
  # end
end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < ApplicationController
  before_action :require_login?, except: [:show, :unlock]
  def like
    article = Article.find(params[:id])

    if current_user.liked_articles.include?(article)
      # 移除讚
      current_user.liked_articles.destroy(article)
      render json: {state: "unliked", id: params[:id]}
    else
      # 新增讚
      current_user.liked_articles << article
      render json: {state: "liked", id: params[:id]}
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_login?, except: [:show, :unlock]
  before_action :find_user_article, only: [:edit, :update, :destroy]
  before_action :find_article, only: [:show, :unlock]
  # before_action :find_article, except: [:create] #如果有加新的action會跟著執行，上面比較明確規範

  def index
    # where 判斷當deleted at沒東西就顯示(案過刪除就不顯示); order desc降冪
    @articles = Article.order(id: :desc)
  end

  def new
    @article = Article.new
  end



  def destroy
    @article.destroy
    # 不是真的刪除，留下點下刪除的時間
    # @article.update(deleted_at: Time.now)
    redirect_to blogs_path 
  end

  def update 
    if @article.update(article_params)
      redirect_to blogs_path
    else
      render :edit
      # render "/articles/edit"
      # redirect_to edit_article_path(@article)
    end
  end
  
  def edit
  end
  
  def show 
    @comment = Comment.new
    @comments = @article.comments.order(id: :desc)
    # Article.find(3) #find直接接id，找不到會直接出錯activeRecord::RecordNotFound，建議使用這種比較激進
    # Article.find_by(id: 3) #find_by可以接id以外的東西，找不到會得到nil
  end

  def unlock
    # 判斷pincode與輸入相同
    if @article.pincode == params[:pincode]
      # 用陣列去記錄解鎖成功的文章id，對應陣列內有出現過就不用重複再解鎖
      set_unlock_articles(@article.id)
      redirect_to article_path(@article)
    else
      redirect_to article_path(@article) , notice: "密碼錯誤"
    end
 end

    
  end
  
  def create
    # clean_params = params.require(:article).permit(:title, :content)
    # clean_params = params[:article].permit(:title, :content)
    # clean後可以避免forbbidon attributes

    # @article = Article.new(article_params)
    # @article.user = current_user
    @article = current_user.articles.new(article_params) #可以省略上面兩行

    if @article.save
      # flash[:notice] = "文章建立成功"
      redirect_to "/", notice: "文章建立成功"
    else
      render "blogs/new"
      #借app/views/blogs/new/html.erb來用
      # redirect_to "blogs/new"
    end
  end
  
  def own?(article)
    article.user == self  
  end

  private
  def article_params
    params.require(:article).permit(:title, :content, :pincode)
  end

  def find_user_article
    @article = current_user.articles.find(params[:id]) 
  end

  def find_article
    @article = Article.find(params[:id]) 
  end

  def set_unlock_articles(article_id)
    # unlock_articles 是自己命名的
    if session[:unlock_articles]
      session[:unlock_articles] << article_id
      session[:unlock_articles].uniq!
    else
      session[:unlock_articles] = [article_id]
    end
  end

app/helpers/api/v1/articles_helper.rb
module Api::V1::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def is_locked?(article)
    article.pincode.present? && !session[:unlock_articles]&.include?(article.id)
  end
end

app/views/articles/_form.html.erb
<%# _form 局部渲染 partial view %>
<%# 拿掉@article 改成 article，不要讓partial view的檔案裏面依賴實體變數git %>

<%= form_for article do |form| %>
標題:
<%= form.text_field :title %>
內容:
<%= form.text_area :content %>
密碼:
<%= form.text_field :pincode %>
貼心小提示，如不需設定可留白

<%= form.submit %>
<% end %>


app/views/articles/edit.html.erb
<h1>編輯文章</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>文章列表</h1>
<%# <a href="/blogs/new">新增文章</a> %>
<%= link_to "新增文章", new_blog_path %>



<% @articles.each do |article| %>
<%# 輸出才要加 "=" %>
<ul>
  <li>
     <%#= link_to article.title, article_path(article) %>
     <%= "O" if article.pincode.present? %>
     <%= link_to article.title, article %>
     <%= link_to "編輯", edit_article_path(article)%>
     <%= link_to "刪除", article, method: "delete", data: {confirm: "是否刪除?"} %> 
     <%# 上面會產生nofollow的效果，可以防止爬蟲，也可以method包在data內就不會有nofollow %>
  </li>
</ul>

<% end %>
<%#  製作忘記密碼之類的會需要用到url連回來 %>
<%#= link_to "新增文章", new_blog_url %>

app/views/articles/new.html.erb
<h1>新增文章</h1>

<%= render "articles/form", article: @article %>
<%#= render partial: "articles/form", locals: {article: @article} %> 

<%# form for 會根據屬性的樣子去找到對應的路徑與方法 %>

<%# <input type="text" name="title"> %>
<%# <textarea name="content" id="" cols="30" rows="10"></textarea> %>
<%# <input type="submit" value="新增"> %>

<%# form_tag，用在沒有model或是table的, 通常其他用form_for %>
<%#= form_tag "/blogs" do %>


<%# <form action="/blogs" method="post">
  <input type="text" name="authenticity_token">
  <input type="submit" value="新增">
</form> %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>


<section data-controller="like"
         data-article-id="<%= @article.id %>"
         data-liked="<%= current_user&.liked?(@article) %>">
  <button data-like-target="likeButton"
          data-action="click->like#like_article">☆</button>
</section>
<%# <button>★</button> %>

<p>
  <%# 如果form for 的方法會抓到model裡面存好的pincode，就會顯示出密碼，應改用 form tag的方式就不會 %>
  <% if is_locked?(@article) %>
    <%# & 表示前面有的話再檢查後面的條件 %>
    <%= form_with url: unlock_article_path(@article), method: "patch" do |f|%>  
      輸入密碼: <%= f.text_field :pincode %>
      <%= f.submit "送出" %>
    <% end %>
  <% else %>
    <%= @article.content %>
  <% end %>
</p>   

<section>
  <%#= form_with model: @comment, url: article_comments_path(@article) do |f| %>
  <%# local: false， form with原本打過去類型是html, 現在打過去在回傳的類型會變成js, 會找到js.erb檔案, 就可以做到前後端分離。 %>
  <%= form_with model: [@article, @comment], local: false do |f| %>
  <%= f.label :content, "留言區" %>
  <%= f.text_area :content %>
  <%= f.submit "送出" %>
  <% end %>


<ul class="comment_list">
  <%# @comments.each do |comment| %>
    <%# 不要在迴圈裏面render 效能差 %>
    <%#= render "comments/comment", comment: comment %>
    <%#= render partial: "comments/comment", collection: @comments, as: :comment %>
    <%#符合 (1)partial view在views/comments/_comment.html.erb，(2)區域變數是comment ，可以簡化成以下 %>
    <%= render @comments %>
  <%# end %>
</ul>


</section>